// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfq0pHX32AKIaOhif3LpQEgUtld_PROis',
    appId: '1:402475127054:web:6f20d00825c1401a3e475f',
    messagingSenderId: '402475127054',
    projectId: 'ns-smart-home',
    authDomain: 'ns-smart-home.firebaseapp.com',
    databaseURL: 'https://ns-smart-home-default-rtdb.firebaseio.com',
    storageBucket: 'ns-smart-home.appspot.com',
    measurementId: 'G-ZFSJ2HWS07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnKJSJVUbnqvdy3TEUDidfu1TZkcDOe4',
    appId: '1:402475127054:android:34375d61e22c31203e475f',
    messagingSenderId: '402475127054',
    projectId: 'ns-smart-home',
    databaseURL: 'https://ns-smart-home-default-rtdb.firebaseio.com',
    storageBucket: 'ns-smart-home.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnuhzAlx8hLeoccAxQnGmjTQBNHHcw0zs',
    appId: '1:402475127054:ios:32dad56443b3ad933e475f',
    messagingSenderId: '402475127054',
    projectId: 'ns-smart-home',
    databaseURL: 'https://ns-smart-home-default-rtdb.firebaseio.com',
    storageBucket: 'ns-smart-home.appspot.com',
    iosClientId: '402475127054-ko3im4rr2tp184l9p3sgc70j75t9qmdb.apps.googleusercontent.com',
    iosBundleId: 'com.nimmalasujith.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnuhzAlx8hLeoccAxQnGmjTQBNHHcw0zs',
    appId: '1:402475127054:ios:32dad56443b3ad933e475f',
    messagingSenderId: '402475127054',
    projectId: 'ns-smart-home',
    databaseURL: 'https://ns-smart-home-default-rtdb.firebaseio.com',
    storageBucket: 'ns-smart-home.appspot.com',
    iosClientId: '402475127054-ko3im4rr2tp184l9p3sgc70j75t9qmdb.apps.googleusercontent.com',
    iosBundleId: 'com.nimmalasujith.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfq0pHX32AKIaOhif3LpQEgUtld_PROis',
    appId: '1:402475127054:web:562ae3a24e538c913e475f',
    messagingSenderId: '402475127054',
    projectId: 'ns-smart-home',
    authDomain: 'ns-smart-home.firebaseapp.com',
    databaseURL: 'https://ns-smart-home-default-rtdb.firebaseio.com',
    storageBucket: 'ns-smart-home.appspot.com',
    measurementId: 'G-95JM0V96SH',
  );

}